# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://todos-database:5432/todos
quarkus.datasource.username=jws
quarkus.datasource.password=jws

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# HTTP
quarkus.http.port=8080

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

# Health
quarkus.health.extensions.enabled=true

# Dev mode
%dev.quarkus.log.console.level=INFO
